apiVersion: v1
kind: Service
metadata:
  name: nginx-green
  labels:
    name: nginx-green
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    name: nginx
    version: "1.11"
  type: LoadBalancer